### ISSUE TITLE
Crash when overriding component

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1014]
- **Version:** Git Master Branch
- **OS:** Windows

In the attached project, when the user goes to the entity tree tab and expands world->gp_IntDispenser->Selector_Button->InteractionPoint->Physics Shape and override it the editor crashes.
[OverrideCrash.zip](https://github.com/OurMachinery/themachinery-public/files/8049858/OverrideCrash.zip)

It crashes in random places every time, so attaching a callstack is pointless.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
(Thank you for reporting these crashes on the Entity Tree and sorry for the time you lost, I made some big changes to it in the past two weeks that introduced some regressions).

**Comment by Tisten** [comment]
I still have this crash when getting latest master. Please double-check that you pushed the commit. Otherwise re-check the fix
