### ISSUE TITLE
Error message when opening gameplay-first-person project

### ISSUE THREAD

**Issue by InjaEm** [OurMachinery/themachinery-public#246]
EDITOR VERSION : beta-2020.5.a
SAMPLES VERSION : sample-projects-2020.5.a ---> gameplay-first-person

Since this is a completely different example project from my other post, I figured I would share the error messages I ran across.  The program ran once though, but the errors shown up after I stopped and hit the reset button.

Also, after closing the simulate tab / window, more errors show up.

Here is a couple pictures to show what is going on.
![resultederrors](https://user-images.githubusercontent.com/66333818/83699005-ee6b2000-a5d0-11ea-80dc-3b5e628c4eda.png)

![resultederrors2](https://user-images.githubusercontent.com/66333818/83699131-46a22200-a5d1-11ea-9174-3c75ac463e22.png)

**Comment by InjaEm** [comment]
OK after testing the gameplay-third-person example, I am seeing similar results. So I'll just post it here and you could probably close the other thread since it's related to the older version of TheMachinery.

![resultederrors3](https://user-images.githubusercontent.com/66333818/83699413-f24b7200-a5d1-11ea-96b9-a77abb736f0a.png)

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.6.

**Comment by InjaEm** [comment]
Still not resolved.

Same problem with 2020.6.

To reproduce it, click play, then click pause, then click that reset button that I am circling in the picture. You will see the error messages. ALL of the same code does this.

![results](https://user-images.githubusercontent.com/66333818/85214096-cc91cd00-b334-11ea-82f1-21ba7b2c6f43.png)
