### ISSUE TITLE
tmbuild hangs on execute_std when trying to find vs version vis vswhere

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#525]

**Comment by niklas-ourmachinery** [comment]
Reported by @khskarl on Discord:

https://discord.com/channels/690290013585408136/779314091990319104/826994266042531900

Might be related to the hang I fixed in `execute_stdout()` when the output is empty, fix here:

https://github.com/OurMachinery/themachinery/commit/856172da69dfa8e7ea5657700a8e52216daf44d6

(Note that this fix is in master, if this is the problem, we want to cherry pick it to the release branch.)

Not sure why the vswhere output would be empty... @simon-ourmachinery, maybe you can ask @khskarl to to run it from the command line.

**Comment by khskarl** [comment]
For the sake of archiving and centrality, adding the screenshot I had sent to Simon earlier:
![image](https://user-images.githubusercontent.com/13659144/113507411-9965a680-9520-11eb-94b1-7ea18b560e02.png)

Line `1181` is where it hangs, the execution flow never returns and arrives to line `1183`.

**Comment by simon-ourmachinery** [comment]
OurMachinery/themachinery@856172d does not solve the issue. confirmed with @khskarl. Found a solution on MSDN. Will validate potential fix again with @khskarl and push if successful.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  fix validated with @khskarl
